import { createSlice } from "@reduxjs/toolkit";

const productsSlice = createSlice({
  name: "products",
  initialState: [
    {
      id: 1,
      name: "Cycle 1",
      image: "/photos/img_01.png",
      price: "$100",
      description: "This is a description of the product",
      quantity: 1,
      featured: true,
      category: "bike",
    },
    {
      id: 2,
      name: "Cycle 2",
      image: "/photos/img_01.png",
      price: "$200",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "bike",
    },
    {
      id: 3,
      name: "Cycle 3",
      image: "/photos/img_01.png",
      price: "$300",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "gloves",
    },
    {
      id: 4,
      name: "Cycle 4",
      image: "/photos/img_01.png",
      price: "$400",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "helmet",
    },
    {
      id: 5,
      name: "Cycle 5",
      image: "/photos/img_01.png",
      price: "$500",
      description: "This is a description of the product",
      quantity: 1,
      featured: true,
      category: "wheels",
    },
    {
      id: 6,
      name: "Cycle 6",
      image: "/photos/img_01.png",
      price: "$300",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "gloves",
    },
    {
      id: 7,
      name: "Cycle 7",
      image: "/photos/img_01.png",
      price: "$400",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "helmet",
    },
    {
      id: 8,
      name: "Cycle 8",
      image: "/photos/img_01.png",
      price: "$500",
      description: "This is a description of the product",
      quantity: 1,
      featured: true,
      category: "wheels",
    },
    {
      id: 9,
      name: "Cycle 9",
      image: "/photos/img_01.png",
      price: "$100",
      description: "This is a description of the product",
      quantity: 1,
      featured: true,
      category: "bike",
    },
    {
      id: 10,
      name: "Cycle 10",
      image: "/photos/img_01.png",
      price: "$200",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "bike",
    },
    {
      id: 11,
      name: "Cycle 1",
      image: "/photos/img_01.png",
      price: "$300",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "gloves",
    },
    {
      id: 16,
      name: "Cycle 16",
      image: "/photos/img_01.png",
      price: "$400",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "helmet",
    },
    {
      id: 12,
      name: "Cycle 12",
      image: "/photos/img_01.png",
      price: "$500",
      description: "This is a description of the product",
      quantity: 1,
      featured: true,
      category: "wheels",
    },
    {
      id: 13,
      name: "Cycle 13",
      image: "/photos/img_01.png",
      price: "$300",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "gloves",
    },
    {
      id: 14,
      name: "Cycle 14",
      image: "/photos/img_01.png",
      price: "$400",
      description: "This is a description of the product",
      quantity: 1,
      featured: false,
      category: "helmet",
    },
    {
      id: 15,
      name: "Cycle 15",
      image: "/photos/img_01.png",
      price: "$500",
      description: "This is a description of the product",
      quantity: 1,
      featured: true,
      category: "wheels",
    },
  ],
  reducers: {},
});

export default productsSlice.reducer;
